---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
# Здесь настройки для офисного окружения, тк у нас специфические параметры открытых ресурсов, работы DNS и сертификатов для HTTP инспекций
  - name: Change ssh config
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication'
      line: PasswordAuthentication no
  - name: create ssh dir for root
    file:
      path: /root/.ssh
      state: directory
  - name: refreshing reps (office)
    ansible.builtin.file:
      path: /etc/apt/sources.list
      state: absent
  - name: refreshing reps (office)
    lineinfile:
      path: /etc/apt/sources.list
      line: deb http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
      create: yes
  - name: refreshing reps (office)
    lineinfile:
      path: /etc/apt/sources.list
      line: deb http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
  - name: refreshing reps (office)
    lineinfile:
      path: /etc/apt/sources.list
      line: deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
  - name: refreshing reps (office)
    lineinfile:
      path: /etc/apt/sources.list
      line: deb http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  - name: Add root key
    lineinfile:
      path: /root/.ssh/authorized_keys
      line: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCni3IaoM12JXT7WIfz4SCqNTvwD0Ff54OZGkTb2q1Y8xdPNb1vCKfNs9uLhvOkFP+yIoL1PlOYx3C7ENBZbenzHSNzhdr06VSEvYy1S34O0Zy2PrXbvwq7YTKF3CzOwd7teZLS/CjXvqyq5EsE3smXWKT9v2bIW9fG2L0tObXAMfk+JH62vl7R0ViFY>
  - name: create https inspections dir (office)
    file:
      path: /usr/local/share/ca-certificates/
      state: directory
  - name: copy first http inspection certs (office)
    copy:
      src: /home/seregin/scripts/edu/11-04/sys-pattern-homework/files/ansible/https_inspect.crt
      dest: /usr/local/share/ca-certificates/
  - name: copt second https instpection cert
    copy:
      src: /home/seregin/scripts/edu/11-04/sys-pattern-homework/files/ansible/https_inspect2.crt
      dest: /usr/local/share/ca-certificates/
  - name: update certs
    command:
      update-ca-certificates
  - name: fix dns settings
    lineinfile:
      path: /etc/systemd/resolved.conf
      regexp: '^DNS='
      line: DNS=8.8.8.8
  - name: restart dns client
    service:
      name: systemd-resolved
      state: restarted
  - name: apt update
    command:
      apt update
# дальше уже по делу (по домашке)
  - name: install midnight
    apt: name=mc state=present
  - name: install rabbitmq
    apt: name=rabbitmq-server state=present
  - name: install python
    apt: name=python3 state=present
  - name: install pip3
    apt: name=pip state=present
  - name: install pika python module
    ansible.builtin.pip:
     name: pika
  - name: adding nodes to hosts
    ansible.builtin.shell: cat /tmp/hosts | grep VAGRANT >> /etc/hosts
    args:
      executable: /bin/bash
  - name: drop cookie
    ansible.builtin.file:
      path: /var/lib/rabbitmq/.erlang.cookie
      state: absent
  - name: create cookie
    lineinfile:
      path: /var/lib/rabbitmq/.erlang.cookie
      line: oBeNIun6xMxXIBsBHAxczVtz+Bk+13GaF8MJJRM6nqOZG/NoxBWIOiMN
      create: yes
  - name: chmod cokie
    ansible.builtin.shell: chmod 600 /var/lib/rabbitmq/.erlang.cookie
    args:
      executable: /bin/bash
  - name: stop rabbit
    command:
      rabbitmqctl stop_app
  - name: reset rabbit
    command:
      rabbitmqctl reset
  - name: join cluster
    command:
      rabbitmqctl join_cluster rabbit@rmq2
  - name: start rabbit
    command:
      rabbitmqctl start_app
  - name: start web interface
    command:
      rabbitmq-plugins enable rabbitmq_management
